Repository Dimdim28/LMStats, pull requests merged in 2024-07, with the labels that each got.

#5 Add i18n localisation
  package-lock.json
  package.json
  src/App.tsx
  src/components/searchUser/searchUser.tsx
  src/containers/guildStats/guildStats.tsx
  src/containers/header/header.tsx
  src/containers/uploadFile/uploadFile.tsx
  src/containers/userStats/userStats.tsx
  src/context/languageContext.tsx
  src/enums/i18n-text.ts
  src/enums/language.ts
  src/languages/EN.ts
  src/languages/RU.ts
  src/languages/index.ts
  src/main.tsx
Labels: feature

#6 New Header component
  .eslintrc.cjs
  src/App.tsx
  src/components/info-icon/infoIcon.module.scss
  src/components/info-icon/infoIcon.tsx
  src/components/language-toggler/languageToggler.module.scss
  src/components/language-toggler/languageToggler.tsx
  src/containers/header/header.module.scss
  src/containers/header/header.tsx
  src/containers/uploadFile/uploadFile.tsx
  src/context/languageContext.tsx
  src/enums/i18n-text.ts
  src/enums/storage.ts
  src/helpers/initLanguage.ts
  src/helpers/setLanguage.ts
  src/languages/EN.ts
  src/languages/RU.ts
  src/styles/_variables.scss
Labels: feature

#8 Add info page
  src/App.tsx
  src/components/crossIcon/crossIcon.module.scss
  src/components/crossIcon/crossIcon.tsx
  src/constants/index.tsx
  src/containers/guildStats/guildStats.tsx
  src/containers/header/header.module.scss
  src/containers/header/header.tsx
  src/containers/info/info.module.scss
  src/containers/info/info.tsx
  src/enums/i18n-text.ts
  src/hooks/useInfoPageData.ts
  src/languages/EN.ts
  src/languages/RU.ts
  src/types/infoData.ts
Labels: feature

#9 Fix Info Page
  src/components/checkbox/checkbox.module.scss
  src/components/line/line.module.scss
  src/components/title/title.tsx
  src/components/userLine/userLine.module.scss
  src/containers/header/header.module.scss
  src/containers/header/header.tsx
  src/containers/info/info.module.scss
  src/languages/EN.ts
  src/languages/RU.ts
  src/styles/_common.scss
  src/styles/_fonts.scss
  src/styles/_nullstyle.scss
Labels: bug, style

#10 Second application release
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/components/checkbox/checkbox.module.scss
  src/components/crossIcon/crossIcon.module.scss
  src/components/crossIcon/crossIcon.tsx
  src/components/info-icon/infoIcon.module.scss
  src/components/info-icon/infoIcon.tsx
  src/components/language-toggler/languageToggler.module.scss
  src/components/language-toggler/languageToggler.tsx
  src/components/line/line.module.scss
  src/components/searchUser/searchUser.tsx
  src/components/title/title.tsx
  src/components/userLine/userLine.module.scss
  src/constants/index.tsx
  src/containers/guildStats/guildStats.tsx
  src/containers/header/header.module.scss
  src/containers/header/header.tsx
  src/containers/info/info.module.scss
  src/containers/info/info.tsx
  src/containers/uploadFile/uploadFile.tsx
  src/containers/userStats/userStats.tsx
  src/context/languageContext.tsx
  src/enums/i18n-text.ts
  src/enums/language.ts
  src/enums/storage.ts
  src/helpers/initLanguage.ts
  src/helpers/setLanguage.ts
  src/hooks/useInfoPageData.ts
  src/languages/EN.ts
  src/languages/RU.ts
  src/languages/index.ts
  src/main.tsx
  src/styles/_common.scss
  src/styles/_fonts.scss
  src/styles/_nullstyle.scss
  src/styles/_variables.scss
  src/types/infoData.ts
Labels: feature

#11 Info page
  src/App.tsx
  src/languages/RU.ts
Labels: bug, style

#12 style: make user stats page more responsive
  src/components/line/line.module.scss
  src/components/title/title.module.scss
  src/containers/userStats/userStats.module.scss
Labels: style

#13 SEO fixes
  index.html
  src/styles/index.scss
Labels: bug

#14 Seo improvements
  index.html
  src/App.tsx
  src/components/line/line.module.scss
  src/components/title/title.module.scss
  src/containers/guildStats/guildStats.tsx
  src/containers/index.ts
  src/containers/uploadFile/uploadFile.tsx
  src/containers/userStats/userStats.module.scss
  src/containers/userStats/userStats.tsx
  src/languages/RU.ts
  src/styles/index.scss
Labels: SEO

#15 Custom preloader
  src/App.tsx
  src/components/Preloader/preloader.module.scss
  src/components/Preloader/preloader.tsx
  src/components/index.ts
  tsconfig.tsbuildinfo
Labels: SEO

#16 Preloader, meta tags, imports
  src/App.tsx
  src/components/Preloader/preloader.module.scss
  src/components/Preloader/preloader.tsx
  src/components/index.ts
  src/containers/guildStats/guildStats.tsx
  src/containers/index.ts
  src/containers/uploadFile/uploadFile.tsx
  src/containers/userStats/userStats.tsx
  tsconfig.tsbuildinfo
Labels: SEO

#17 test: remove lazy
  src/App.tsx
Labels: invalid
